language: python
python:
  - "2.7"
  - "3.5"
  - "nightly"
# command to install dependencies
addons:
  apt_packages:
    - swig
    - libpcsclite-dev
install:
  - "pip install --upgrade pip"
  - "pip install wheel"
  - "pip wheel ."
  - "pip install ."
# command to run tests
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then MIFAREACR122.py -h; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then apc-channel.py -h; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then apc-pr-log.py -h; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then base64dump.py -h; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then disitool.py -h; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then emldump.py -h; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then extractscripts.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then file2vbscript.py -h; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then image-forensics-ela.py -h; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then lookup-ips.py -h; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then make-pdf-embedded.py -h; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then make-pdf-javascript.py -h; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then make-pdf-jbig2.py -h; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then oledump.py -h; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pecheck.py -h; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pdfid.py -h; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then shellcode2vba.py -h; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then shellcode2vbscript.py -h; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then virustotal-search.py -h; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then virustotal-submit.py -h; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then vs.py -h; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then wsrtool.py -h; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then zipdump.py -h; fi
  - apc-b.py -h
  - cisco-calculate-ssh-fingerprint.py -h
  - count.py -h
  - defuzzer.py -h
  - find-file-in-file.py -h
  - format-bytes.py -h
  - hash.py -h
  - image-overlay.py -h
  - lookup-hosts.py -h
  - nmap-xml-script-output.py -h
  - pcap-rename.py -h
  - pdf-parser.py -h
  - peid-userdb-to-yara-rules.py -h
  - re-search.py -h
  - simple-shellcode-generator.py -h
  - split.py -h
  - translate.py -h
  - what-is-new.py -h
  - xmldump.py -h
