environment:
  global:
    APPVEYOR_PYTHON_URL: "https://raw.githubusercontent.com/ogrisel/python-appveyor-demo/master/appveyor/"

    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor-nodeps\\run_with_env.cmd"

  matrix:

    # Pre-installed Python versions, which Appveyor may upgrade to
    # a later point release.

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x" # currently 2.7.9
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x" # currently 2.7.9
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.3.x" # currently 3.3.5
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python33-x64"
      PYTHON_VERSION: "3.3.x" # currently 3.3.5
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.x" # currently 3.4.3
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.x" # currently 3.4.3
      PYTHON_ARCH: "64"

    # Also test a Python version not pre-installed
    # See: https://github.com/ogrisel/python-appveyor-demo/issues/10

    - PYTHON: "C:\\Python266"
      PYTHON_VERSION: "2.6.6"
      PYTHON_ARCH: "32"

install:
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""

  # Download the Appveyor Python build accessories into subdirectory .\appveyor
  - mkdir appveyor-nodeps
  - ps: $wc = new-object net.webclient
  - ps: $run = $wc.DownloadString($env:APPVEYOR_PYTHON_URL + 'run_with_env.cmd')
  - ps: $run | Out-File -Encoding ascii -FilePath appveyor-nodeps\run_with_env.cmd
  - ps: $install = $wc.DownloadString($env:APPVEYOR_PYTHON_URL + 'install.ps1')
  - ps: $install | Out-File -Encoding ascii -FilePath appveyor-nodeps\install.ps1

  # Install Python (from the official .msi of http://python.org) and pip when
  # not already installed.
  - "powershell ./appveyor-nodeps/install.ps1"

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Swig for smartcard
  - choco install swig -y
  # Install the build dependencies of the project. If some dependencies contain
  # compiled extensions and are not provided as pre-built wheel packages,
  # pip will build them from source using the MSVC compiler matching the
  # target Python version and architecture
  - "%CMD_IN_ENV% pip install ."

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - apc-b.py -h
  - find-file-in-file.py -h
  - make-pdf-javascript.py -h
  - pecheck.py -h
  - split.py -h
  - apc-channel.py -h
  - image-forensics-ela.py -h
  - make-pdf-jbig2.py -h
  - peid-userdb-to-yara-rules.py -h
  - translate.py -h
  - apc-pr-log.py -h
  - image-overlay.py -h
  - MIFAREACR122.py -h
  - virustotal-search.py -h
  - base64dump.py -h
  - defuzzer.py -h
  - nmap-xml-script-output.py -h
  - virustotal-submit.py -h
  - cisco-calculate-ssh-fingerprint.py -h
  - disitool.py -h
  - lookup-hosts.py -h
  - oledump.py -h
  - re-search.py -h
  - vs.py -h
  - count.py -h
  - emldump.py -h
  - lookup-ips.py -h
  - pcap-rename.py -h
  - shellcode2vba.py -h
  - wsrradial.py -h
  - extractscripts.py
  - make-pdf-embedded.py -h
  - pdfid.py -h
  - shellcode2vbscript.py -h
  - wsrtool.py -h
  - file2vbscript.py -h
  - make-pdf-helloworld.py -h
  - pdf-parser.py -h
  - simple-shellcode-generator.py -h
  - zipdump.py -h

after_test:
  # If tests are successful, create binary packages for the project.
  - "%CMD_IN_ENV% python setup.py bdist_wheel"
  - "%CMD_IN_ENV% python setup.py bdist_wininst"
  - "%CMD_IN_ENV% python setup.py bdist_msi"
  - ps: "ls dist"

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  - path: dist\